import { USERS_MANAGEMENT_PACKAGE_NAME, USERS_MANAGEMENT_SERVICE_NAME } from "common/grpc";

export const PACKAGE_NAME = USERS_MANAGEMENT_PACKAGE_NAME;
export const SERVICE_NAME = USERS_MANAGEMENT_SERVICE_NAME;
