import { AUTHENTICATION_PACKAGE_NAME, AUTHENTICATION_SERVICE_NAME } from "common/grpc";

export const PACKAGE_NAME = AUTHENTICATION_PACKAGE_NAME;
export const SERVICE_NAME = AUTHENTICATION_SERVICE_NAME;
