version: "3.7"

services:
    db:
        container_name: database
        image: postgres:15.2
        restart: always
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - ${DB_PORT}:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
